export enum ErrorCode{
    UNAUTHORIZED,
    NETWORK_ERROR,


    PERMISSION_DENIED_TO_CHANGE_TRAVEL = 100,
    UNEXPECTED_TRAVEL_ID,
    PERMISSION_DENIED_DELETE_TRAVEL,
    UNEXPECTED_PLACE,


    EXPENSE_PERMISSION_DENIED=200,


    PERMISSION_DENIED_CHANGE_LIMIT=300,
    LOW_LIMIT_VALUE,
}