name: Continuous Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: sftp
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: build
        run: npm run build

      - name: deploy file to server
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_USER: 'root'
          REMOTE_HOST: '${{ secrets.MAC_IP }}'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: 'build/'
          TARGET: '/home/bitrix/www/'
          sftpArgs: '-o ConnectTimeout=5'
          # sftp_only: true
          password: ${{secrets.SSH_PASSWORD}}
          # delete_remote_files: true