name: Continuous Deploy
on:
  push:
    branches:
      - 'no branch'

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: sftp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: build
        run: npm run build:development

      - name: deploy file to server
        uses:  wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '${{ secrets.MAC_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: '/home/bitrix/ext_www/dev.travelerapp.ru'
          sftpArgs: '-o ConnectTimeout=5'
          # sftp_only: true
          password: ${{secrets.SSH_PASSWORD}}
          delete_remote_files: 'true'